#' Generate Conditionally Independent `R`-Many MA(4) Varying Time Series of the Same Length
#'
#' @description
#' The MA(4) that is used as the base coefficients for the variation is `(-.3,-.6,-.3,.6)`. This is based on the MA(4) used in \insertCite{granados-garcia_brain_2022;textual}{HBEST}.
#' 
#' @details
#' The variation around the base theta coefficients is generated by:
#' 1. Sample 4 values from a \eqn{N(0,1)} to use as a "mean".
#' 2. Calculate: `basetheta + alpha * mu_r * abs(basetheta)` where `basetheta` is the original coefficients; `mu_r` is the 4 sampled values from the \eqn{N(0,1)}; and `alpha` is the user-specified scalar that controls the variation around the base coefficients. 
#' 3. Generate: A new time-series using the new `theta` value from step 2.
#' 4. Repeat steps 1-3 `R`-many times.
#'
#' @param n A scalar indicating the length of all `R` time series.
#' @param R A scalar indicating the number of conditionally independent time series to be generated.
#' @param burn A scalar indicating the amount of burn-in to be used with [stats::arima.sim()].
#' @param alpha A scalar indicating the 
#'
#' @returns
#' @export
#'
#' @examples
generate_MA4_vary = function(n = 1000, R = 1, burn = 50, alpha = 0.05){
  # create matrix to store the time series
  ts_list <- vector(mode = "list", length = R)
  # create matrix to store "true" theta values
  theta_true <- matrix(NA, nrow = 4, ncol = R)
  # create matrix to store mu_r values
  mu_r_gen <- matrix(NA, nrow = 4, ncol = R)
  # set AR parameter
  phi <- NULL
  # set MA parameter
  basetheta <- c(-.3,-.6,-.3,.6)
  for (r in 1:R) {
    # Take each theta from the baseline theta
    # sample from a N(0,1) to get a mu_r
    mu_r = rnorm(n = length(basetheta), mean = 0, sd = 1)
    # calculate: theta_r + alpha * |theta_r| * mu_r
    theta = basetheta + alpha * mu_r * abs(basetheta)
    # store MA(1) coefficient generated
    theta_true[,r] <- theta
    # store mu_r
    mu_r_gen[,r] <- mu_r
    # generate data
    ts_list[[r]] <- matrix(stats::arima.sim(model = list(ar = phi, ma = theta), n = n_vary[r], sd = 1, n.start = burn), ncol = 1)
  }
  return(list(
    "ts_list" = ts_list,
    "theta_true" = theta_true,
    "alpha" = alpha,
    "mu_r_gen" = mu_r_gen
  ))
  
  
  
  
  # S=arima.sim(n = size, list(ma=c(-.3,-.6,-.3,.6)  ), sd = 1, n.start = 10000)
  #standarized serie
  # S=(S-mean(S))/sd(S)
  
}